from pathlib import Path

S=Path('app/src/main/java/com/gy/rotarapida/WhatsRouteAccessibilityService.kt')
s=S.read_text(encoding='utf-8')

old_header='===== DIAGNOSTICO TEXTO v24 | TEXT v6 + SKIP IMMEDIATE PROOF + READ MORE v21 + DIRECT SEND ====='
new_header='===== DIAGNOSTICO TEXTO v25 | TEXT v6 + POST PROOF DIAG + READ MORE v21 + DIRECT SEND ====='
required=[
    old_header,
    'private fun analyzeCurrentWindow() {',
    'val tdAnalyzeLocal = SystemClock.elapsedRealtime()',
    'val tdCollectDoneLocal = SystemClock.elapsedRealtime()',
    'val tfParseStart = SystemClock.elapsedRealtime()',
    'val tfParseDone = SystemClock.elapsedRealtime()',
    'if(proof.expanded){',
    'proofV24=skipImmediate=true | firstProofDelay=6ms | strictProof=preserved',
    'speedDiagnosticSendMethod = "TEXT_DIRECT_V5"',
    '===== DIAGNOSTICO IMAGEM v9 | BAIRRO FIRST + GAIOLA NARROW + DIRECT SEND + BULK PIXELS =====',
]
for m in required:
    if m not in s:
        raise SystemExit('POST PROOF DIAG v25 wrong base: '+m)

# Diagnostic-only state. No parser, proof rule, delay, click, send or image behavior changes.
state_anchor='    private var tdV23PollLate1=-1L\n'
state_insert=state_anchor+'''    private var rmV25ProofConfirmedAt=0L
    private var rmV25ReanalyzeAt=0L
    private var rmV25CollectDoneAt=0L
    private var rmV25ParserStartAt=0L
    private var rmV25ParserDoneAt=0L
    private var tdV25ProofConfirmedAt=0L
    private var tdV25ReanalyzeAt=0L
    private var tdV25CollectDoneAt=0L
    private var tdV25ParserStartAt=0L
    private var tdV25ParserDoneAt=0L
    private var tdV25RouteAt=0L
'''
if state_anchor not in s:
    raise SystemExit('v25 state anchor not found')
s=s.replace(state_anchor,state_insert,1)

# Mark the exact instant the strict proof succeeds. rmExpanded keeps exactly the
# same value it had before; the new variable merely copies that timestamp.
proof_old='''        if(proof.expanded){
            rmExpanded=SystemClock.elapsedRealtime(); rmPolls=poll; rmPending=false; rmCarry=true
            handler.post{analyzeCurrentWindow()}
            return
        }
'''
proof_new='''        if(proof.expanded){
            rmExpanded=SystemClock.elapsedRealtime(); rmV25ProofConfirmedAt=rmExpanded; rmPolls=poll; rmPending=false; rmCarry=true
            handler.post{analyzeCurrentWindow()}
            return
        }
'''
if proof_old not in s:
    raise SystemExit('v25 proof-success anchor not found')
s=s.replace(proof_old,proof_new,1)

# Capture the reanalysis entry generated by proof success. This is independent of
# the old tdAnalyze timestamp, which can represent a later analyzer invocation.
analyze_anchor='''        val tdAnalyzeLocal = SystemClock.elapsedRealtime()
'''
analyze_insert=analyze_anchor+'''        if(rmCarry && rmV25ProofConfirmedAt>0L && rmV25ReanalyzeAt==0L){
            rmV25ReanalyzeAt=tdAnalyzeLocal
        }
'''
if analyze_anchor not in s:
    raise SystemExit('v25 analyze anchor not found')
s=s.replace(analyze_anchor,analyze_insert,1)

# Capture completion of the full initial tree collection in that reanalysis.
collect_anchor='''        val tdCollectDoneLocal = SystemClock.elapsedRealtime()
'''
collect_insert=collect_anchor+'''        if(rmCarry && rmV25ProofConfirmedAt>0L && rmV25CollectDoneAt==0L){
            rmV25CollectDoneAt=tdCollectDoneLocal
        }
'''
if collect_anchor not in s:
    raise SystemExit('v25 collect anchor not found')
s=s.replace(collect_anchor,collect_insert,1)

# Split the post-proof gap around the existing expanded-bubble parser. Timing only.
parse_start_old='''            val tfParseStart = SystemClock.elapsedRealtime()
            val tfRoute = if(rmCarry){
'''
parse_start_new='''            val tfParseStart = SystemClock.elapsedRealtime()
            if(rmCarry && rmV25ProofConfirmedAt>0L) rmV25ParserStartAt=tfParseStart
            val tfRoute = if(rmCarry){
'''
if parse_start_old not in s:
    raise SystemExit('v25 parse-start anchor not found')
s=s.replace(parse_start_old,parse_start_new,1)

parse_done_old='''            val tfParseDone = SystemClock.elapsedRealtime()

            if(rmCarry && tfRoute==null){
'''
parse_done_new='''            val tfParseDone = SystemClock.elapsedRealtime()
            if(rmCarry && rmV25ProofConfirmedAt>0L) rmV25ParserDoneAt=tfParseDone

            if(rmCarry && tfRoute==null){
'''
if parse_done_old not in s:
    raise SystemExit('v25 parse-done anchor not found')
s=s.replace(parse_done_old,parse_done_new,1)

# Snapshot absolute timestamps BEFORE tdBegin clears the Read-more state.
success_old='''                currentStartedAt = SystemClock.elapsedRealtime()
                tdBegin(
'''
success_new='''                currentStartedAt = SystemClock.elapsedRealtime()
                if(rmV25ProofConfirmedAt>0L){
                    tdV25ProofConfirmedAt=rmV25ProofConfirmedAt
                    tdV25ReanalyzeAt=rmV25ReanalyzeAt
                    tdV25CollectDoneAt=rmV25CollectDoneAt
                    tdV25ParserStartAt=rmV25ParserStartAt
                    tdV25ParserDoneAt=rmV25ParserDoneAt
                    tdV25RouteAt=currentStartedAt
                }
                tdBegin(
'''
if success_old not in s:
    raise SystemExit('v25 route snapshot anchor not found')
s=s.replace(success_old,success_new,1)

# Reset only temporary per-attempt state alongside the existing v23/v24 Read-more reset.
reset_anchor='''rmV23LastPostAt=0L; rmV23PollGap1=-1L; rmV23PollLate1=-1L'''
reset_insert=reset_anchor+'''; rmV25ProofConfirmedAt=0L; rmV25ReanalyzeAt=0L; rmV25CollectDoneAt=0L; rmV25ParserStartAt=0L; rmV25ParserDoneAt=0L'''
if reset_anchor not in s:
    raise SystemExit('v25 reset anchor not found')
s=s.replace(reset_anchor,reset_insert,1)

# Report the exact post-proof split. tdD keeps malformed/stale samples visible as --.
report_anchor='''                appendLine("proofV24=skipImmediate=true | firstProofDelay=6ms | strictProof=preserved")
'''
report_insert=report_anchor+'''                if(tdV25ProofConfirmedAt>0L){
                    appendLine("postProofV25=proof->reanalyze=${tdD(tdV25ProofConfirmedAt,tdV25ReanalyzeAt)} | reanalyze->collect=${tdD(tdV25ReanalyzeAt,tdV25CollectDoneAt)} | collect->parser=${tdD(tdV25CollectDoneAt,tdV25ParserStartAt)} | parser=${tdD(tdV25ParserStartAt,tdV25ParserDoneAt)} | parserDone->route=${tdD(tdV25ParserDoneAt,tdV25RouteAt)} | proof->route=${tdD(tdV25ProofConfirmedAt,tdV25RouteAt)}")
                }
'''
if report_anchor not in s:
    raise SystemExit('v25 report anchor not found')
s=s.replace(report_anchor,report_insert,1)

s=s.replace(old_header,new_header,1)

for m in [
    new_header,
    'rmV25ProofConfirmedAt=rmExpanded',
    'rmV25ReanalyzeAt=tdAnalyzeLocal',
    'rmV25CollectDoneAt=tdCollectDoneLocal',
    'rmV25ParserStartAt=tfParseStart',
    'rmV25ParserDoneAt=tfParseDone',
    'postProofV25=proof->reanalyze=',
    'proofV24=skipImmediate=true | firstProofDelay=6ms | strictProof=preserved',
    'scheduleV22=${tdV22RequestedDelay}ms',
    'speedDiagnosticSendMethod = "TEXT_DIRECT_V5"',
    '===== DIAGNOSTICO IMAGEM v9 | BAIRRO FIRST + GAIOLA NARROW + DIRECT SEND + BULK PIXELS =====',
]:
    if m not in s:
        raise SystemExit('POST PROOF DIAG v25 verify failed: '+m)

S.write_text(s,encoding='utf-8')
print('POST PROOF DIAG v25 applied: proof->reanalyze->collect->parser->route timing only; v24/v21/TEXT v6/IMAGE v9 behavior preserved')
